[workspace]
authors = ["drbongo"]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "ashcore"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=26.4.0,<27"
